
import { pgTable, text, serial, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// === TABLE DEFINITIONS ===

// Users are created when a valid serial key is used
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull(), // User can set a display name
  serialKey: text("serial_key").notNull().unique(), // The key they used to login
  role: text("role").notNull().default("user"), // 'owner' or 'user'
  expiresAt: timestamp("expires_at"), // Null for permanent, set for limited time
  createdAt: timestamp("created_at").defaultNow(),
  ringtoneUrl: text("ringtone_url"),
  muteNotifications: boolean("mute_notifications").default(false),
  coins: integer("coins").notNull().default(0),
  decorationId: integer("decoration_id"),
  nameStyleId: integer("name_style_id"),
});

// Shop Items (Decorations and Name Stylers)
export const shopItems = pgTable("shop_items", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  type: text("type").notNull(), // 'decoration' or 'name_style'
  price: integer("price").notNull(),
  imageUrl: text("image_url"), // For decorations (PNG overlay)
  cssStyles: text("css_styles"), // For name stylers (JSON string)
  createdAt: timestamp("created_at").defaultNow(),
});

// User Inventory
export const userInventory = pgTable("user_inventory", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  itemId: integer("item_id").notNull().references(() => shopItems.id),
  purchasedAt: timestamp("purchased_at").defaultNow(),
});

// Keys generated by the owner for others to use
export const accessKeys = pgTable("access_keys", {
  id: serial("id").primaryKey(),
  key: text("key").notNull().unique(),
  type: text("type").notNull(), // 'permanent' or 'limited'
  durationMinutes: integer("duration_minutes"), // If limited
  createdBy: integer("created_by").references(() => users.id),
  isUsed: boolean("is_used").default(false),
  createdAt: timestamp("created_at").defaultNow(),
});

// Search history
export const searchHistory = pgTable("search_history", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  query: text("query"),
  url: text("url").notNull(),
  visitedAt: timestamp("visited_at").defaultNow(),
});

// Group Chats
export const groupChats = pgTable("group_chats", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  inviteCode: text("invite_code").notNull().unique(),
  ownerId: integer("owner_id").notNull().references(() => users.id),
  createdAt: timestamp("created_at").defaultNow(),
});

// GC Members
export const groupChatMembers = pgTable("group_chat_members", {
  id: serial("id").primaryKey(),
  groupId: integer("group_id").notNull().references(() => groupChats.id),
  userId: integer("user_id").notNull().references(() => users.id),
  joinedAt: timestamp("joined_at").defaultNow(),
});

// Update messages to support GCs and media
export const messages = pgTable("messages", {
  id: serial("id").primaryKey(),
  senderId: integer("sender_id").notNull().references(() => users.id),
  recipientId: integer("recipient_id").references(() => users.id),
  groupId: integer("group_id").references(() => groupChats.id),
  content: text("content").notNull(),
  mediaUrl: text("media_url"),
  mediaType: text("media_type"), // 'image', 'video', 'audio'
  replyToId: integer("reply_to_id"), // ID of message being replied to
  createdAt: timestamp("created_at").defaultNow(),
});

// === RELATIONS ===
export const usersRelations = relations(users, ({ many }) => ({
  history: many(searchHistory),
  sentMessages: many(messages, { relationName: "sender" }),
  receivedMessages: many(messages, { relationName: "recipient" }),
  createdKeys: many(accessKeys),
  groups: many(groupChatMembers),
}));

export const groupChatsRelations = relations(groupChats, ({ one, many }) => ({
  owner: one(users, { fields: [groupChats.ownerId], references: [users.id] }),
  members: many(groupChatMembers),
  messages: many(messages),
}));

export const groupChatMembersRelations = relations(groupChatMembers, ({ one }) => ({
  group: one(groupChats, { fields: [groupChatMembers.groupId], references: [groupChats.id] }),
  user: one(users, { fields: [groupChatMembers.userId], references: [users.id] }),
}));

export const messagesRelations = relations(messages, ({ one }) => ({
  sender: one(users, {
    fields: [messages.senderId],
    references: [users.id],
    relationName: "sender",
  }),
  recipient: one(users, {
    fields: [messages.recipientId],
    references: [users.id],
    relationName: "recipient",
  }),
  group: one(groupChats, {
    fields: [messages.groupId],
    references: [groupChats.id],
  }),
}));

// === BASE SCHEMAS ===
export const insertUserSchema = createInsertSchema(users).omit({ id: true, createdAt: true });
export const insertKeySchema = createInsertSchema(accessKeys).omit({ id: true, isUsed: true, createdAt: true });
export const insertHistorySchema = createInsertSchema(searchHistory).omit({ id: true, visitedAt: true });
export const insertMessageSchema = createInsertSchema(messages).omit({ id: true, createdAt: true });

// === EXPLICIT API CONTRACT TYPES ===

export type User = typeof users.$inferSelect;
export type AccessKey = typeof accessKeys.$inferSelect;
export type HistoryItem = typeof searchHistory.$inferSelect;
export type Message = typeof messages.$inferSelect;

// Auth
export type LoginRequest = { serialKey: string; username?: string };
export type LoginResponse = { user: User; token: string }; // Simple session/token response

// Keys
export type CreateKeyRequest = { type: 'permanent' | 'limited'; durationMinutes?: number };
export type KeyResponse = AccessKey;

// History
export type CreateHistoryRequest = { url: string; query?: string };

// Chat
export type CreateMessageRequest = { content: string; recipientId?: number }; // If recipientId is omitted, it's public
export type MessageWithUser = Message & { senderName: string; replyToContent?: string | null; replyToSenderName?: string | null };

// Proxy
export type ProxyRequest = { url: string };

